name: CI

on:
  workflow_dispatch:
    # push:
    #     branches:
    #         - master
    #         - next
    #         - beta
    #         - alpha
    #         - "*.x"
    # pull_request:
    #     types:
    #         - opened
    #         - synchronize
permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
      id-token: write

jobs:
    build_release:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - run: docker build --tag janlishak/srp-docker-example .
            - name: Login to ghcr.io docker registry
              run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            - name: Release
              uses: actions/setup-node@v2
              with:
                  cache: npm
            - run: npm ci --ignore-scripts
            - run: npx semantic-release-plus --debug
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
